# numpy basic-01

https://docs.scipy.org/doc/numpy/user/basics.creation.html
https://docs.scipy.org/doc/numpy/user/basics.indexing.html
http://cs231n.github.io/python-numpy-tutorial/

In [35]:
import numpy as np
a = np.arange(15).reshape((3, 5))

In [36]:
# the number of axes (dimensions) of the array
print(a.ndim)
# the dimensions of the array
# the length of the shape tuple is the number of axes, ndim
print(a.shape)
print(a.dtype.name)
print(a.itemsize)
print(type(a))
print(a.size)
# the buffer containing the actual elements of the array. Normally, we won't need to use this attribute.
print(a.data)
a = np.array(1, 2, 3, 4)
print(a)

2
(3, 5)
int64
8
<class 'numpy.ndarray'>
15


ValueError: only 2 non-keyword arguments accepted

In [37]:
print(np.array([[1, 5], [2, 4]]))
print(np.array([(1, 5), (2, 4)]))

array([[1, 5],
       [2, 4]])

In [17]:
np.array(np.arange(4).reshape((2, 2)), dtype=complex)

array([[0.+0.j, 1.+0.j],
       [2.+0.j, 3.+0.j]])

In [19]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones(( 2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [21]:
np.empty((2, 3))

array([[6.92217681e-310, 4.68425857e-310, 0.00000000e+000],
       [0.00000000e+000, 6.92216579e-310, 0.00000000e+000]])

In [22]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [25]:
np.linspace(2, 3, 10, dtype=np.float16)

array([2.   , 2.111, 2.223, 2.334, 2.445, 2.555, 2.666, 2.777, 2.889,
       3.   ], dtype=float16)

In [26]:
np.linspace(2, 3, 10, dtype=np.float32)

array([2.       , 2.1111112, 2.2222223, 2.3333333, 2.4444444, 2.5555556,
       2.6666667, 2.7777777, 2.8888888, 3.       ], dtype=float32)

## Indexing

In [34]:
x = np.arange(10)
print(x[2])
print(x[-2])
x.shape = (2, 5)
print(x)
print(x[1, 3])
print(x[1, -1])
print(x[0])

2
8
[[0 1 2 3 4]
 [5 6 7 8 9]]
8
9
[0 1 2 3 4]


In [39]:
print(x[0][2]) # inefficient as a new temporary array is created after the first index that is subsequently indexed by 2
print(x[0, 2])

2
2


NumPy uses C-order indexing. That means that the last index usually represents the most rapidly chaning memory location, where the first index represents the most rapidly changing location in memory. This difference represents a great potential for confusion.

In [41]:
x = np.arange(10)
print(x[2:5])
print(x[:-7])
print(x[1:7:2])
y = np.arange(35).reshape(5, 7)
print(y[1:5:2, ::3])


[2 3 4]
[0 1 2]
[1 3 5]
[[ 7 10 13]
 [21 24 27]]


## Index arrays

NumPy arrays may be indexed with other arrays (or any other sequence-like object that can be converted to an array, such as lists, with the exception of tuples; see the end of this document for why this is). The use of index arrays ranges from simple, straightforward cases to complex, hard-to-understand cases. For all cases of index arrays, what is returned is a copy of the original data, now a view as one gets for slices.

Index arrays must be of integer type. Each value in the array indicates which value in the array to use in place of index. To illustrate:

In [44]:
x = np.arange(10, 1, -1)
print(x)
print(x[np.array([3, 3, 1, 8])])
print(x[np.array([3, 3, -3, 8])])
print(x[np.array([3, 3, 20, 8])])

[10  9  8  7  6  5  4  3  2]
[7 7 9 2]
[7 7 4 2]


IndexError: index 20 is out of bounds for axis 1 with size 9

In [45]:
print(x[np.array([[1, 1], [2, 3]])])

[[9 9]
 [8 7]]


In [48]:
print(y)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [49]:
print(y[np.array([0, 2, 4]), np.array([0, 1, 2])])

[ 0 15 30]


In [51]:
# The broadcasting mechanism permits index arrays to be combined with scalars for other indices.
# The effect is that the scalar value is used for all the corresponding values of the index arrays
print(y[np.array([0, 2, 4]), 1])

[ 1 15 29]


In [53]:
# It is possible to only partially index an array with index arrays
# An example of where this may be useful is for a color lookup table 
# where we want to map the values of an image to RGB triples for display.
# The lookup table could have a shape (nlookup, 3). Indexing such an array with an image
# with shape (ny, nx) with dtype=np.uint8 will result in an array of shape (ny, nx, 3) where
# a triple of RGB values is associated with each pixel location.
print(y[np.array([0, 2, 4])])

[[ 0  1  2  3  4  5  6]
 [14 15 16 17 18 19 20]
 [28 29 30 31 32 33 34]]


## Boolean or "mask" index arrays

In [57]:
b = y > 20
print(b)
# Unlike in the case of integer index arrays, in the boolean case, the result is a 1-D array containing
# all the elements in the indexed array corresponding to all the true elements in the boolean array.
print(y[b])
print(y[np.nonzero(b)])
# As with index arrays, what is returned is a copy of the data, not a view as one gets with slices.

[[False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]]
[21 22 23 24 25 26 27 28 29 30 31 32 33 34]
[21 22 23 24 25 26 27 28 29 30 31 32 33 34]


In [56]:
# The result will be multidimensional if y has more dimensions than b.
print(b[:, 5])
print(y[b[:, 5]])

[False False False  True  True]
[[21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [58]:
x = np.arange(30).reshape(2, 3, 5)
print(x)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [60]:
b = np.array([[True, True, False], [False, True, True]])
print(x[b])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [20 21 22 23 24]
 [25 26 27 28 29]]


## Combining index arrays with slices

In [63]:
print(y)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [64]:
# In effect, the slice is converted to an index array np.array([[ 1, 2]]) (shape (1, 2))  that is
# broadcast with the index array to produce a resultant array of shape (3, 2).
print(y[np.array([0, 2, 4]), 1:3])

[[ 1  2]
 [15 16]
 [29 30]]


In [67]:
# Likewise, slicing can be combined with broadcasted boolean indices
b = y > 20
print(b)
print(y[b[:, 5], 1:3])

[[False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]]
[[22 23]
 [29 30]]


## Structural indexing tools

In [69]:
print(y)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [70]:
print(y.shape)
# the np.newaxis object can be used within array indices to add new dimensions with a size of 1.
print(y[:, np.newaxis, :].shape)

(5, 7)
(5, 1, 7)


In [73]:
# Note that there are no new elements in the array, just that the dimensionality is increased.
# This can be handy to combine two arrays in a way that otherwise would require explicitly reshaping
# operations. For example:
x = np.arange(5)
print(x[:, np.newaxis])
print(x[np.newaxis, :])
print(x[:, np.newaxis] + x[np.newaxis, :])

[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]]
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


In [75]:
# The ellipsis syntax maybe used to indicate selecting in full any remaining unspecified dimensions.
z = np.arange(81).reshape(3, 3, 3, 3)
print(z)

[[[[ 0  1  2]
   [ 3  4  5]
   [ 6  7  8]]

  [[ 9 10 11]
   [12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]
   [24 25 26]]]


 [[[27 28 29]
   [30 31 32]
   [33 34 35]]

  [[36 37 38]
   [39 40 41]
   [42 43 44]]

  [[45 46 47]
   [48 49 50]
   [51 52 53]]]


 [[[54 55 56]
   [57 58 59]
   [60 61 62]]

  [[63 64 65]
   [66 67 68]
   [69 70 71]]

  [[72 73 74]
   [75 76 77]
   [78 79 80]]]]


In [76]:
print(z[1, ..., 2])

[[29 32 35]
 [38 41 44]
 [47 50 53]]


In [77]:
# This is equivalent to
print(z[1, :, :, 2])

[[29 32 35]
 [38 41 44]
 [47 50 53]]


## Assigning values to indexed arrays

In [81]:
x = np.arange(10)
x[2:7] = 1
print(x)
# or an array of the right size
x[2:7] = np.arange(5)
print(x)

[0 1 1 1 1 1 1 7 8 9]
[0 1 0 1 2 3 4 7 8 9]


In [108]:
x = np.arange(0, 50, 10)
print(x)

[ 0 10 20 30 40]


In [109]:
# Where people expect that the first location will be incremented by 3. In fact,
# it will only be incremented by 1. The reason is because a new array is extracted from
# the original (as a temporary) containing the values at 1, 1, 3, 1, then the value 1 is added
# to the temporary, and then the temporary is assigned back to the original array.
# Thus the value of the array at x[1]+1 is assigned to x[1] three times, rather than being
# incremented 3 times.
a = x[np.array([1, 1, 3, 1])]
a += 1
print(a)
x[np.array([1, 1, 3, 1])] += 1
# why x is not 4-dim??
print(x)

[11 11 31 11]
[ 0 11 20 31 40]


In [104]:
x= np.arange(0, 50, 10)
index_array = np.array([1, 1, 3, 1])
temp_array = x[index_array]
print(temp_array)
temp_array += 1
x = temp_array
print(x)

[10 10 30 10]
[11 11 31 11]


## Dealing with variable numbers of indices within programs

In [99]:
print(z)

[[[[ 0  1  2]
   [ 3  4  5]
   [ 6  7  8]]

  [[ 9 10 11]
   [12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]
   [24 25 26]]]


 [[[27 28 29]
   [30 31 32]
   [33 34 35]]

  [[36 37 38]
   [39 40 41]
   [42 43 44]]

  [[45 46 47]
   [48 49 50]
   [51 52 53]]]


 [[[54 55 56]
   [57 58 59]
   [60 61 62]]

  [[63 64 65]
   [66 67 68]
   [69 70 71]]

  [[72 73 74]
   [75 76 77]
   [78 79 80]]]]


In [100]:
indices = (1, 1, 1, 1)
print(z[indices])

40


In [101]:
indices = (1, Ellipsis, 1) # same as [1, ..., 1]
print(z[indices])

[[28 31 34]
 [37 40 43]
 [46 49 52]]


In [103]:
# Because the special treatment of tuples, they are not automatically converted to an 
# array as a list would be.
print(z[[1, 1, 1, 1]]) # produces a large array
print(z[(1, 1, 1, 1)]) # produces a single value

[[[[27 28 29]
   [30 31 32]
   [33 34 35]]

  [[36 37 38]
   [39 40 41]
   [42 43 44]]

  [[45 46 47]
   [48 49 50]
   [51 52 53]]]


 [[[27 28 29]
   [30 31 32]
   [33 34 35]]

  [[36 37 38]
   [39 40 41]
   [42 43 44]]

  [[45 46 47]
   [48 49 50]
   [51 52 53]]]


 [[[27 28 29]
   [30 31 32]
   [33 34 35]]

  [[36 37 38]
   [39 40 41]
   [42 43 44]]

  [[45 46 47]
   [48 49 50]
   [51 52 53]]]


 [[[27 28 29]
   [30 31 32]
   [33 34 35]]

  [[36 37 38]
   [39 40 41]
   [42 43 44]]

  [[45 46 47]
   [48 49 50]
   [51 52 53]]]]
40
